### ISSUE TITLE
fix(qadams): proxy branches bypass AxiosHttpClient, leaking request body and Authorization header into run output

### ISSUE THREAD

**Issue by binalirustamov** [aiqadam/qadam-flow#402]
Raised by the `app-sec` and `code-quality` gates on #401, which closed #400 for the `httpClient`
path. This is the same leak class through a different door, and #401 does not close it.

## The bypass

Two qadams call axios **directly** on their proxy branch instead of going through `AxiosHttpClient`:

- `packages/qadams/core/graphql/src/lib/actions/query.ts:137-142`
- `packages/qadams/community/http-oauth2/src/lib/actions/send-oauth2-http-request.ts:~235`

```ts
const axiosClient = axios.create({ httpsAgent });
const proxied_response = await axiosClient.request(request);
```

A failure there throws a raw `AxiosError`, not an `HttpError`. `AxiosError` keeps `config` as an own
enumerable property, and `config` holds both `data` (the request body) and `headers` (including
`Authorization`). The engine formats every thrown error with
`formatQadamError(err, { raw: inspect(err) })` (`packages/server/engine/src/lib/utils.ts:49`), and
`inspect` at default depth prints all of it into `FriendlyQadamError.raw` — persisted, and rendered
verbatim under **Technical Details** at
`packages/web/src/app/builder/data-display/friendly-error-view.tsx:89`.

So this path leaks strictly *more* than the one #400 was about: the body **and** the auth header.
Readable by any project member with `READ_RUN`, which includes the read-only VIEWER role.

## Second defect on the same lines

Both proxy branches fall into:

```ts
} catch (error) {
  if (failsafe) {
    return (error as HttpError).errorMessage();
  }
```

`errorMessage` is not a method on an `AxiosError`. Whenever a proxy is configured, `failsafe`
("No Error on Failure") does not return the failsafe output — it throws
`TypeError: (intermediate value).errorMessage is not a function`. The cast is what hides this; it is
also a standing violation of the no-type-casting rule in CLAUDE.md. `error instanceof HttpError` is
both the convention-correct narrowing and the fix.

## Scope note

`grep` finds 9 qadam files importing `axios` directly. Whether all of them are exposed the same way
has not been checked — worth establishing before picking a fix shape, since the answer decides
between patching two call sites and routing proxy support through `AxiosHttpClient` (which already
takes an `axiosClient` argument, so the plumbing exists).

## Provenance

Not introduced by #401. `git blame` should be run before attributing it to anyone.

**Comment by binalirustamov** [comment]
Triage: labelled **P1**, `security`, `track/product-qadams` (it had none of the three).

`security` because the leaked material is the request body plus the `Authorization` header, rendered verbatim under Technical Details and readable by any project member with `READ_RUN` — which includes the read-only VIEWER role. P1 rather than P0 because it requires a configured proxy on one of the two affected qadams, so it is not the default path. The second defect on the same lines (`failsafe` throwing `TypeError: ... errorMessage is not a function` whenever a proxy is set) is a plain correctness bug at the same priority.
